export type ThemeId =
  | "futuristic-infra"
  | "desert-tech-minimal"
  | "carbon-black"
  | "arctic-data"
  | "arabian-luxury"
  | "industrial-grid"
  | "quantum-blue"
  | "emerald-vision"
  | "sunset-desert"
  | "platinum-edge"
  | "hearst-corporation"
  // Web3 / Crypto
  | "ethereum-protocol"
  | "solana-gradient"
  | "bitcoin-orange"
  | "defi-dune"
  | "nft-gallery"
  // Enterprise Tech
  | "vercel-dark"
  | "linear-purple"
  | "palantir-navy"
  | "bloomberg-terminal"
  | "nvidia-dgx"
  // High-End / Luxury Tech
  | "stripe-gradient"
  | "pitch-midnight"
  | "ghost-editorial"
  | "apple-silicon"
  | "arc-iris";

export interface ColorPalette {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  surface: string;
  surfaceAlt: string;
  text: string;
  textMuted: string;
  border: string;
  highlight: string;
  cmyk: { primary: string; secondary: string; accent: string };
}

export interface Typography {
  headingFont: string;
  bodyFont: string;
  monoFont: string;
  heroSize: string;
  titleSize: string;
  subtitleSize: string;
  bodySize: string;
  captionSize: string;
  headingWeight: string;
  letterSpacing: string;
}

export interface ArtDirection {
  id: ThemeId;
  name: string;
  tagline: string;
  colors: ColorPalette;
  typography: Typography;
  photoStyle: string;
  graphicStyle: string;
  iconography: string;
  boxStyle: string;
  titleStyle: string;
  dividerStyle: string;
  dataVizStyle: string;
  globalTone: string;
  tailwind: {
    bg: string;
    bgSurface: string;
    bgSurfaceAlt: string;
    text: string;
    textMuted: string;
    accent: string;
    border: string;
    highlight: string;
    headerBg: string;
    footerBg: string;
  };
}

const themes: Record<string, ArtDirection> = {
  "futuristic-infra": {
    id: "futuristic-infra",
    name: "Futuristic Infra",
    tagline: "Architecture du futur, données du présent",
    colors: {
      primary: "#0A0E1A",
      secondary: "#0D2137",
      accent: "#00D4FF",
      background: "#05080F",
      surface: "#0F1929",
      surfaceAlt: "#162235",
      text: "#E8F4FF",
      textMuted: "#6B8FAA",
      border: "#1A3A5C",
      highlight: "#00D4FF",
      cmyk: { primary: "C:100 M:80 Y:0 K:85", secondary: "C:95 M:55 Y:0 K:70", accent: "C:100 M:0 Y:0 K:0" },
    },
    typography: {
      headingFont: "'Space Grotesk', sans-serif",
      bodyFont: "'Inter', sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "clamp(48px, 6vw, 96px)",
      titleSize: "clamp(24px, 3vw, 48px)",
      subtitleSize: "clamp(14px, 1.8vw, 24px)",
      bodySize: "clamp(10px, 1.2vw, 14px)",
      captionSize: "clamp(8px, 0.9vw, 10px)",
      headingWeight: "700",
      letterSpacing: "-0.02em",
    },
    photoStyle: "Longue exposition nocturne, LED bleues, cooling towers illuminés",
    graphicStyle: "Grilles hexagonales, lignes de circuit, hologrammes data",
    iconography: "Monoline tech, contours lumineux sur fond sombre",
    boxStyle: "Glassmorphism sombre, border cyan, backdrop-blur",
    titleStyle: "Majuscules, gradient bleu-cyan, ombre portée luminescente",
    dividerStyle: "Lignes pointillées cyan animées, dégradés lumineux",
    dataVizStyle: "Barres néon cyan sur fond sombre, glow effect, data streams",
    globalTone: "Technologique, mystérieux, premium futuriste",
    tailwind: {
      bg: "bg-[#05080F]",
      bgSurface: "bg-[#0F1929]",
      bgSurfaceAlt: "bg-[#162235]",
      text: "text-[#E8F4FF]",
      textMuted: "text-[#6B8FAA]",
      accent: "text-[#00D4FF]",
      border: "border-[#1A3A5C]",
      highlight: "text-[#00D4FF]",
      headerBg: "bg-[#0A0E1A]",
      footerBg: "bg-[#05080F]",
    },
  },

  "desert-tech-minimal": {
    id: "desert-tech-minimal",
    name: "Desert Tech Minimal",
    tagline: "La puissance du désert rencontre la précision digitale",
    colors: {
      primary: "#F5EFE0",
      secondary: "#E8D5B0",
      accent: "#C17F3E",
      background: "#FAF6EE",
      surface: "#F0E8D5",
      surfaceAlt: "#E8DCC5",
      text: "#1A1410",
      textMuted: "#7A6A55",
      border: "#D4BF9A",
      highlight: "#C17F3E",
      cmyk: { primary: "C:0 M:4 Y:12 K:4", secondary: "C:0 M:12 Y:30 K:9", accent: "C:0 M:38 Y:68 K:24" },
    },
    typography: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "clamp(40px, 5.5vw, 88px)",
      titleSize: "clamp(20px, 2.8vw, 44px)",
      subtitleSize: "clamp(12px, 1.6vw, 20px)",
      bodySize: "clamp(10px, 1.1vw, 13px)",
      captionSize: "clamp(7px, 0.8vw, 9px)",
      headingWeight: "300",
      letterSpacing: "0.04em",
    },
    photoStyle: "Aérien désert, textures sable macro, silhouettes architecture",
    graphicStyle: "Lignes fines géométriques, espaces blancs, micro-détails",
    iconography: "Hairline icons, ultra-fin, géométrique minimal",
    boxStyle: "Bordures fines, fond sable léger, ombres douces",
    titleStyle: "Light weight, letterspacing étendu, majuscules aérées",
    dividerStyle: "Lignes fines simples, points réguliers espacés",
    dataVizStyle: "Barres fines beige/bronze, grille légère, annotations minimalistes",
    globalTone: "Épuré, luxueux discret, sophistiqué naturel",
    tailwind: {
      bg: "bg-[#FAF6EE]",
      bgSurface: "bg-[#F0E8D5]",
      bgSurfaceAlt: "bg-[#E8DCC5]",
      text: "text-[#1A1410]",
      textMuted: "text-[#7A6A55]",
      accent: "text-[#C17F3E]",
      border: "border-[#D4BF9A]",
      highlight: "text-[#C17F3E]",
      headerBg: "bg-[#F0E8D5]",
      footerBg: "bg-[#E8DCC5]",
    },
  },

  "carbon-black": {
    id: "carbon-black",
    name: "Carbon Black",
    tagline: "Infrastructure de haut rang, identité sans compromis",
    colors: {
      primary: "#0A0A0A",
      secondary: "#141414",
      accent: "#C9A84C",
      background: "#060606",
      surface: "#111111",
      surfaceAlt: "#1A1A1A",
      text: "#F0F0F0",
      textMuted: "#666666",
      border: "#2A2A2A",
      highlight: "#C9A84C",
      cmyk: { primary: "C:0 M:0 Y:0 K:97", secondary: "C:0 M:0 Y:0 K:92", accent: "C:0 M:16 Y:62 K:21" },
    },
    typography: {
      headingFont: "'Space Grotesk', sans-serif",
      bodyFont: "'Inter', sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "clamp(52px, 7vw, 104px)",
      titleSize: "clamp(26px, 3.2vw, 52px)",
      subtitleSize: "clamp(14px, 1.8vw, 22px)",
      bodySize: "clamp(10px, 1.2vw, 14px)",
      captionSize: "clamp(8px, 0.9vw, 10px)",
      headingWeight: "800",
      letterSpacing: "-0.03em",
    },
    photoStyle: "Noir et blanc contrasté, textures carbone macro, reflets or",
    graphicStyle: "Texture carbone subtile, filets or, géométrie ultra-précise",
    iconography: "Filled gold sur fond noir, poids visuel fort",
    boxStyle: "Fond noir profond, bordure or fine, coin biseauté",
    titleStyle: "Extra-bold noir/blanc, accent or sur lettre clé",
    dividerStyle: "Ligne or fine avec ornement central, filigrane",
    dataVizStyle: "Barres or sur noir, contraste maximal, valeurs en mono",
    globalTone: "Prestige absolu, exclusif, puissance discrète",
    tailwind: {
      bg: "bg-[#060606]",
      bgSurface: "bg-[#111111]",
      bgSurfaceAlt: "bg-[#1A1A1A]",
      text: "text-[#F0F0F0]",
      textMuted: "text-[#666666]",
      accent: "text-[#C9A84C]",
      border: "border-[#2A2A2A]",
      highlight: "text-[#C9A84C]",
      headerBg: "bg-[#0A0A0A]",
      footerBg: "bg-[#060606]",
    },
  },

  "arctic-data": {
    id: "arctic-data",
    name: "Arctic Data",
    tagline: "La clarté des données dans un environnement immaculé",
    colors: {
      primary: "#F8FBFF",
      secondary: "#EBF4FF",
      accent: "#0066FF",
      background: "#FFFFFF",
      surface: "#F2F7FF",
      surfaceAlt: "#E8F1FF",
      text: "#0A1628",
      textMuted: "#5578A0",
      border: "#C8DEFF",
      highlight: "#0066FF",
      cmyk: { primary: "C:2 M:1 Y:0 K:0", secondary: "C:8 M:4 Y:0 K:0", accent: "C:100 M:60 Y:0 K:0" },
    },
    typography: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "clamp(44px, 6vw, 92px)",
      titleSize: "clamp(22px, 3vw, 46px)",
      subtitleSize: "clamp(13px, 1.7vw, 21px)",
      bodySize: "clamp(10px, 1.1vw, 13px)",
      captionSize: "clamp(7px, 0.8vw, 9px)",
      headingWeight: "600",
      letterSpacing: "-0.01em",
    },
    photoStyle: "Installations refroidies, vapeur froide, bleu électrique pur",
    graphicStyle: "Data flow clean, isométrique bleu, grille fine sur blanc",
    iconography: "Outlined bleu, propre, consistant, system icons",
    boxStyle: "Blanc pur, ombre légère bleue, radius généreux",
    titleStyle: "Semi-bold, bleu électrique sur blanc, underline accent",
    dividerStyle: "Dégradé bleu-transparent, largeur variable",
    dataVizStyle: "Barres bleu electric, fond blanc, annotations claires",
    globalTone: "Technique, fiable, institutionnel clair",
    tailwind: {
      bg: "bg-white",
      bgSurface: "bg-[#F2F7FF]",
      bgSurfaceAlt: "bg-[#E8F1FF]",
      text: "text-[#0A1628]",
      textMuted: "text-[#5578A0]",
      accent: "text-[#0066FF]",
      border: "border-[#C8DEFF]",
      highlight: "text-[#0066FF]",
      headerBg: "bg-[#F2F7FF]",
      footerBg: "bg-[#0A1628]",
    },
  },

  "arabian-luxury": {
    id: "arabian-luxury",
    name: "Arabian Luxury",
    tagline: "Héritage millénaire, vision 2030",
    colors: {
      primary: "#1A0A2E",
      secondary: "#2D1045",
      accent: "#D4AF37",
      background: "#0F0620",
      surface: "#1F0D38",
      surfaceAlt: "#2A1448",
      text: "#F5E8D0",
      textMuted: "#9B7E60",
      border: "#4A2860",
      highlight: "#D4AF37",
      cmyk: { primary: "C:46 M:73 Y:0 K:82", secondary: "C:40 M:75 Y:0 K:73", accent: "C:0 M:17 Y:74 K:17" },
    },
    typography: {
      headingFont: "'Space Grotesk', sans-serif",
      bodyFont: "'Inter', sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "clamp(42px, 5.5vw, 88px)",
      titleSize: "clamp(22px, 2.8vw, 44px)",
      subtitleSize: "clamp(12px, 1.6vw, 20px)",
      bodySize: "clamp(10px, 1.1vw, 13px)",
      captionSize: "clamp(7px, 0.85vw, 9px)",
      headingWeight: "600",
      letterSpacing: "0.01em",
    },
    photoStyle: "Architecture islamique contemporaine, dorures, nuit qatarie",
    graphicStyle: "Motifs géométriques arabesques, filigrane or, calligraphie stylisée",
    iconography: "Or sur prune, ornemental, mix tradition/tech",
    boxStyle: "Prune profond, bordure or ornementale, texture velours",
    titleStyle: "Or sur prune, majuscules légèrement serif, prestige",
    dividerStyle: "Ornement géométrique central, filet or double",
    dataVizStyle: "Courbes or sur prune, gradient royal, élégance data",
    globalTone: "Majesteux, visionnaire, ancrage culturel fort",
    tailwind: {
      bg: "bg-[#0F0620]",
      bgSurface: "bg-[#1F0D38]",
      bgSurfaceAlt: "bg-[#2A1448]",
      text: "text-[#F5E8D0]",
      textMuted: "text-[#9B7E60]",
      accent: "text-[#D4AF37]",
      border: "border-[#4A2860]",
      highlight: "text-[#D4AF37]",
      headerBg: "bg-[#1A0A2E]",
      footerBg: "bg-[#0F0620]",
    },
  },

  "industrial-grid": {
    id: "industrial-grid",
    name: "Industrial Grid",
    tagline: "Robustesse industrielle, scalabilité sans limite",
    colors: {
      primary: "#1C2128",
      secondary: "#252D38",
      accent: "#FF6B35",
      background: "#141820",
      surface: "#1E2530",
      surfaceAlt: "#28303C",
      text: "#D8E0EB",
      textMuted: "#6878A0",
      border: "#323E50",
      highlight: "#FF6B35",
      cmyk: { primary: "C:30 M:18 Y:0 K:84", secondary: "C:28 M:16 Y:0 K:78", accent: "C:0 M:58 Y:79 K:0" },
    },
    typography: {
      headingFont: "'Space Grotesk', sans-serif",
      bodyFont: "'Inter', sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "clamp(46px, 6.5vw, 100px)",
      titleSize: "clamp(24px, 3vw, 48px)",
      subtitleSize: "clamp(13px, 1.7vw, 21px)",
      bodySize: "clamp(10px, 1.2vw, 14px)",
      captionSize: "clamp(8px, 0.9vw, 10px)",
      headingWeight: "700",
      letterSpacing: "-0.01em",
    },
    photoStyle: "Rack serveurs, cablage structuré, infrastructure physique",
    graphicStyle: "Grille isométrique, blueprints techniques, annotations",
    iconography: "Bold filled orange, technique, fonctionnel",
    boxStyle: "Fond acier sombre, accent orange, corner tags techniques",
    titleStyle: "Bold caps, accent orange sur dark, style blueprint",
    dividerStyle: "Double trait technique, hash marks de mesure",
    dataVizStyle: "Barres orange/acier, style engineering dashboard",
    globalTone: "Robuste, technique, opérationnel, confiance",
    tailwind: {
      bg: "bg-[#141820]",
      bgSurface: "bg-[#1E2530]",
      bgSurfaceAlt: "bg-[#28303C]",
      text: "text-[#D8E0EB]",
      textMuted: "text-[#6878A0]",
      accent: "text-[#FF6B35]",
      border: "border-[#323E50]",
      highlight: "text-[#FF6B35]",
      headerBg: "bg-[#1C2128]",
      footerBg: "bg-[#141820]",
    },
  },

  "quantum-blue": {
    id: "quantum-blue",
    name: "Quantum Blue",
    tagline: "Traitement des données à l'échelle quantique",
    colors: {
      primary: "#020B1A",
      secondary: "#041528",
      accent: "#00FFD1",
      background: "#010812",
      surface: "#061220",
      surfaceAlt: "#0A1A2E",
      text: "#CCE8FF",
      textMuted: "#3D6E99",
      border: "#0A2A4A",
      highlight: "#00FFD1",
      cmyk: { primary: "C:99 M:84 Y:0 K:90", secondary: "C:98 M:80 Y:0 K:85", accent: "C:100 M:0 Y:18 K:0" },
    },
    typography: {
      headingFont: "'IBM Plex Mono', monospace",
      bodyFont: "'Inter', sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "clamp(44px, 5.8vw, 92px)",
      titleSize: "clamp(22px, 2.8vw, 44px)",
      subtitleSize: "clamp(12px, 1.6vw, 20px)",
      bodySize: "clamp(10px, 1.1vw, 13px)",
      captionSize: "clamp(7px, 0.85vw, 9px)",
      headingWeight: "500",
      letterSpacing: "0.02em",
    },
    photoStyle: "Long exposure data centers, fiber optics, quantum simulations",
    graphicStyle: "Particle systems, node networks, data flow 3D",
    iconography: "Outline phosphore vert/cyan, high-tech, abstract",
    boxStyle: "Glassmorphism vert-bleu, border lumineux, données flottantes",
    titleStyle: "Mono font, caractères lumineux, style terminal",
    dividerStyle: "Ligne de code, wave data, particules",
    dataVizStyle: "Network graphs phosphorescents, flows temps réel, matrices",
    globalTone: "Avant-garde, scientifique, puissance computationnelle",
    tailwind: {
      bg: "bg-[#010812]",
      bgSurface: "bg-[#061220]",
      bgSurfaceAlt: "bg-[#0A1A2E]",
      text: "text-[#CCE8FF]",
      textMuted: "text-[#3D6E99]",
      accent: "text-[#00FFD1]",
      border: "border-[#0A2A4A]",
      highlight: "text-[#00FFD1]",
      headerBg: "bg-[#020B1A]",
      footerBg: "bg-[#010812]",
    },
  },

  "emerald-vision": {
    id: "emerald-vision",
    name: "Emerald Vision",
    tagline: "Infrastructure durable, avenir vert garanti",
    colors: {
      primary: "#042E1A",
      secondary: "#063D24",
      accent: "#00E676",
      background: "#021510",
      surface: "#073A20",
      surfaceAlt: "#0A4828",
      text: "#C8F5DC",
      textMuted: "#4D9066",
      border: "#0D5530",
      highlight: "#00E676",
      cmyk: { primary: "C:99 M:0 Y:55 K:82", secondary: "C:99 M:0 Y:45 K:76", accent: "C:100 M:0 Y:54 K:10" },
    },
    typography: {
      headingFont: "'Space Grotesk', sans-serif",
      bodyFont: "'Inter', sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "clamp(46px, 6vw, 96px)",
      titleSize: "clamp(23px, 2.9vw, 46px)",
      subtitleSize: "clamp(13px, 1.7vw, 21px)",
      bodySize: "clamp(10px, 1.2vw, 14px)",
      captionSize: "clamp(8px, 0.9vw, 10px)",
      headingWeight: "700",
      letterSpacing: "-0.02em",
    },
    photoStyle: "Panneaux solaires, verdure, data center eco-responsable",
    graphicStyle: "Organique géométrique, feuilles circuit, biomorphique tech",
    iconography: "Vert émeraude, nature+tech hybride, leaves+chips",
    boxStyle: "Vert profond, border émeraude, texture légère",
    titleStyle: "Vert vif sur fond sombre, nature keywords",
    dividerStyle: "Courbe organique verte, growth line",
    dataVizStyle: "Barres croissance verte, KPIs sustainability, area charts",
    globalTone: "Responsable, ambitieux, tourné vers l'avenir durable",
    tailwind: {
      bg: "bg-[#021510]",
      bgSurface: "bg-[#073A20]",
      bgSurfaceAlt: "bg-[#0A4828]",
      text: "text-[#C8F5DC]",
      textMuted: "text-[#4D9066]",
      accent: "text-[#00E676]",
      border: "border-[#0D5530]",
      highlight: "text-[#00E676]",
      headerBg: "bg-[#042E1A]",
      footerBg: "bg-[#021510]",
    },
  },

  "sunset-desert": {
    id: "sunset-desert",
    name: "Sunset Desert",
    tagline: "Quand l'ambition rencontre l'horizon du Golfe",
    colors: {
      primary: "#1A0A05",
      secondary: "#2D1508",
      accent: "#FF7B2C",
      background: "#120704",
      surface: "#1E0D06",
      surfaceAlt: "#2A1208",
      text: "#FFE8D0",
      textMuted: "#9B6040",
      border: "#4A2010",
      highlight: "#FF7B2C",
      cmyk: { primary: "C:0 M:60 Y:80 K:90", secondary: "C:0 M:55 Y:75 K:82", accent: "C:0 M:52 Y:83 K:0" },
    },
    typography: {
      headingFont: "'Space Grotesk', sans-serif",
      bodyFont: "'Inter', sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "clamp(44px, 5.8vw, 92px)",
      titleSize: "clamp(22px, 2.8vw, 44px)",
      subtitleSize: "clamp(12px, 1.6vw, 20px)",
      bodySize: "clamp(10px, 1.1vw, 13px)",
      captionSize: "clamp(7px, 0.85vw, 9px)",
      headingWeight: "700",
      letterSpacing: "-0.01em",
    },
    photoStyle: "Couchers de soleil qataris, silhouettes gratte-ciels, skyline dorée",
    graphicStyle: "Dégradés chauds, horizons géométriques, sable en mouvement",
    iconography: "Orange chaud, filled, évocateur chaleur/énergie",
    boxStyle: "Brun sombre, border orange, chaleur visuelle",
    titleStyle: "Orange feu sur brun sombre, dynamique, élan",
    dividerStyle: "Horizon gradient orange-brun, ondulation",
    dataVizStyle: "Barres orange-rouge, palette chaleur, soleil data",
    globalTone: "Passionné, visionnaire, ancrage géographique fort",
    tailwind: {
      bg: "bg-[#120704]",
      bgSurface: "bg-[#1E0D06]",
      bgSurfaceAlt: "bg-[#2A1208]",
      text: "text-[#FFE8D0]",
      textMuted: "text-[#9B6040]",
      accent: "text-[#FF7B2C]",
      border: "border-[#4A2010]",
      highlight: "text-[#FF7B2C]",
      headerBg: "bg-[#1A0A05]",
      footerBg: "bg-[#120704]",
    },
  },

  "platinum-edge": {
    id: "platinum-edge",
    name: "Platinum Edge",
    tagline: "Précision absolue, exécution sans faille",
    colors: {
      primary: "#0D0D0D",
      secondary: "#161616",
      accent: "#E8E8E8",
      background: "#080808",
      surface: "#121212",
      surfaceAlt: "#1C1C1C",
      text: "#F5F5F5",
      textMuted: "#707070",
      border: "#282828",
      highlight: "#FFFFFF",
      cmyk: { primary: "C:0 M:0 Y:0 K:95", secondary: "C:0 M:0 Y:0 K:91", accent: "C:0 M:0 Y:0 K:9" },
    },
    typography: {
      headingFont: "'Inter', sans-serif",
      bodyFont: "'Inter', sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "clamp(48px, 6.5vw, 104px)",
      titleSize: "clamp(24px, 3.2vw, 52px)",
      subtitleSize: "clamp(13px, 1.8vw, 22px)",
      bodySize: "clamp(10px, 1.2vw, 14px)",
      captionSize: "clamp(8px, 0.9vw, 10px)",
      headingWeight: "800",
      letterSpacing: "-0.04em",
    },
    photoStyle: "Noir et blanc HQ, abstraction pure, ombres dramatiques",
    graphicStyle: "Swiss grid, typographie pure, maximum whitespace",
    iconography: "Ultra-thin blanc sur noir, système iconique pur",
    boxStyle: "Noir absolu, contour blanc fin, minimalisme total",
    titleStyle: "Condensed extra-bold, blanc pur sur noir, typographie sculpture",
    dividerStyle: "1px blanc opaque, respiration maximale",
    dataVizStyle: "Blanc/gris sur noir, précision chirurgicale, élégance data",
    globalTone: "Absolu, luxe invisible, maîtrise totale",
    tailwind: {
      bg: "bg-[#080808]",
      bgSurface: "bg-[#121212]",
      bgSurfaceAlt: "bg-[#1C1C1C]",
      text: "text-[#F5F5F5]",
      textMuted: "text-[#707070]",
      accent: "text-[#E8E8E8]",
      border: "border-[#282828]",
      highlight: "text-white",
      headerBg: "bg-[#0D0D0D]",
      footerBg: "bg-[#080808]",
    },
  },

  "hearst-corporation": {
    id: "hearst-corporation",
    name: "Hearst Corporation",
    tagline: "Mining institutionnel, infrastructure durable, vision éditoriale",
    colors: {
      primary: "#FFFFFF",        // white
      secondary: "#F6FEF3",      // mint-green-lightest
      accent: "#A7FB90",         // mint-green (signature)
      background: "#FFFFFF",
      surface: "#FCFDFC",        // gin-lightest
      surfaceAlt: "#F6FEF3",     // mint-green-lightest
      text: "#000000",           // neutral-darkest
      textMuted: "#5C605C",      // gin-darker
      border: "rgba(0,0,0,0.15)",// neutral-darkest @ 15% (border officielle)
      highlight: "#A7FB90",      // mint-green
      cmyk: { primary: "C:0 M:0 Y:0 K:0", secondary: "C:3 M:0 Y:3 K:0", accent: "C:34 M:0 Y:43 K:2" },
    },
    typography: {
      headingFont: "Fkgrotesktrial, Arial, sans-serif",
      bodyFont: "Fkgrotesktrial, Arial, sans-serif",
      monoFont: "'IBM Plex Mono', monospace",
      heroSize: "5rem",          // heading-style-h1
      titleSize: "3rem",         // heading-style-h2
      subtitleSize: "1.5rem",    // heading-style-h5
      bodySize: "1rem",          // text-size-regular
      captionSize: "0.75rem",    // text-size-tiny
      headingWeight: "400",      // FK Grotesk Regular pour les H sur le site
      letterSpacing: "-0.03rem", // letter-spacing h2
    },
    photoStyle: "Photographie éditoriale clean, panneaux solaires, hardware mining, lumière naturelle, ratios mixtes",
    graphicStyle: "Whitespace généreux, grille fluide, typographie comme architecture, micro-illustrations dotted",
    iconography: "SVG monoline noir, tracé fin uniforme, géométrie simple",
    boxStyle: "Cartes blanches, border-radius 1rem, bordure rgba(0,0,0,.15) 1px, ombre soft",
    titleStyle: "FK Grotesk Regular 400, letter-spacing -0.03rem, casse normale, noir sur blanc",
    dividerStyle: "Filet 1px rgba(0,0,0,.15), respiration verticale large",
    dataVizStyle: "Barres mint-green #A7FB90 sur blanc, libellés noir, grille minimale",
    globalTone: "Éditorial corporate clean-tech, institutionnel scandinave, confiance souriante",
    tailwind: {
      bg: "bg-white",
      bgSurface: "bg-[#FCFDFC]",
      bgSurfaceAlt: "bg-[#F6FEF3]",
      text: "text-[#000000]",
      textMuted: "text-[#5C605C]",
      accent: "text-[#A7FB90]",
      border: "border-black/15",
      highlight: "bg-[#A7FB90]",
      headerBg: "bg-white",
      footerBg: "bg-[#000000]",
    },
  },
};

// ─── WEB3 / CRYPTO ────────────────────────────────────────────────────────────

themes["ethereum-protocol"] = {
  id: "ethereum-protocol",
  name: "Ethereum Protocol",
  tagline: "Infrastructure décentralisée, couche de confiance mondiale",
  colors: {
    primary: "#0A0516",
    secondary: "#120A2A",
    accent: "#627EEA",
    background: "#06030F",
    surface: "#0F0820",
    surfaceAlt: "#160D2E",
    text: "#E8E0FF",
    textMuted: "#7060AA",
    border: "#2A1D50",
    highlight: "#8B9CF4",
    cmyk: { primary: "C:75 M:90 Y:0 K:94", secondary: "C:70 M:85 Y:0 K:84", accent: "C:61 M:51 Y:0 K:8" },
  },
  typography: {
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(44px, 5.8vw, 92px)",
    titleSize: "clamp(22px, 2.8vw, 44px)",
    subtitleSize: "clamp(12px, 1.6vw, 20px)",
    bodySize: "clamp(10px, 1.1vw, 13px)",
    captionSize: "clamp(7px, 0.85vw, 9px)",
    headingWeight: "600",
    letterSpacing: "-0.02em",
  },
  photoStyle: "Visualisations blockchain, nodes lumineux, infra décentralisée, violet profond",
  graphicStyle: "Hexagones entrelacés, hash trees, merkle visualisations, grille protocol",
  iconography: "Contours violet-bleu, symboles cryptographiques, hexagones",
  boxStyle: "Glassmorphism violet profond, border #627EEA subtle, backdrop-blur",
  titleStyle: "Space Grotesk Semi-bold, gradient violet→bleu, EIP-style",
  dividerStyle: "Ligne fine violet opacity, hash indicator",
  dataVizStyle: "Courbes on-chain violet/bleu, gas analytics, adoption curves",
  globalTone: "Décentralisé, confiant, ouvert, infrastructure critique",
  tailwind: {
    bg: "bg-[#06030F]",
    bgSurface: "bg-[#0F0820]",
    bgSurfaceAlt: "bg-[#160D2E]",
    text: "text-[#E8E0FF]",
    textMuted: "text-[#7060AA]",
    accent: "text-[#627EEA]",
    border: "border-[#2A1D50]",
    highlight: "text-[#8B9CF4]",
    headerBg: "bg-[#0A0516]",
    footerBg: "bg-[#06030F]",
  },
};

themes["solana-gradient"] = {
  id: "solana-gradient",
  name: "Solana Gradient",
  tagline: "Vitesse absolue, infrastructure haute performance",
  colors: {
    primary: "#030010",
    secondary: "#0A0520",
    accent: "#9945FF",
    background: "#020008",
    surface: "#070318",
    surfaceAlt: "#0D0528",
    text: "#E0D4FF",
    textMuted: "#6040A0",
    border: "#1D0A40",
    highlight: "#14F195",
    cmyk: { primary: "C:70 M:100 Y:0 K:94", secondary: "C:65 M:95 Y:0 K:87", accent: "C:40 M:73 Y:0 K:0" },
  },
  typography: {
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(46px, 6vw, 96px)",
    titleSize: "clamp(23px, 2.9vw, 46px)",
    subtitleSize: "clamp(13px, 1.7vw, 21px)",
    bodySize: "clamp(10px, 1.2vw, 14px)",
    captionSize: "clamp(8px, 0.9vw, 10px)",
    headingWeight: "700",
    letterSpacing: "-0.03em",
  },
  photoStyle: "Rendu 3D low-poly violet-vert, flux de données lumineux, node map",
  graphicStyle: "Gradient multi-spectre, courbes fluides violet→vert, logo mark Solana",
  iconography: "Gradient purple→green, formes fluides, high contrast",
  boxStyle: "Gradient sombre violet→vert border, glass bg, glow vert",
  titleStyle: "Bold, gradient text violet→vert signature, large hero",
  dividerStyle: "Gradient line violet→vert, lumineux",
  dataVizStyle: "TPS charts violet gradient, throughput metrics, vert highlight",
  globalTone: "Ultra-rapide, innovant, challenger du status quo",
  tailwind: {
    bg: "bg-[#020008]",
    bgSurface: "bg-[#070318]",
    bgSurfaceAlt: "bg-[#0D0528]",
    text: "text-[#E0D4FF]",
    textMuted: "text-[#6040A0]",
    accent: "text-[#9945FF]",
    border: "border-[#1D0A40]",
    highlight: "text-[#14F195]",
    headerBg: "bg-[#030010]",
    footerBg: "bg-[#020008]",
  },
};

themes["bitcoin-orange"] = {
  id: "bitcoin-orange",
  name: "Bitcoin Orange",
  tagline: "La valeur absolue, l'infrastructure immuable",
  colors: {
    primary: "#0A0602",
    secondary: "#141005",
    accent: "#F7931A",
    background: "#060401",
    surface: "#100B04",
    surfaceAlt: "#1A1108",
    text: "#FFF8E1",
    textMuted: "#8A6230",
    border: "#2E1C08",
    highlight: "#FFBA50",
    cmyk: { primary: "C:0 M:10 Y:80 K:96", secondary: "C:0 M:10 Y:75 K:92", accent: "C:0 M:40 Y:89 K:3" },
  },
  typography: {
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(48px, 6.5vw, 100px)",
    titleSize: "clamp(24px, 3.2vw, 50px)",
    subtitleSize: "clamp(13px, 1.8vw, 22px)",
    bodySize: "clamp(10px, 1.2vw, 14px)",
    captionSize: "clamp(8px, 0.9vw, 10px)",
    headingWeight: "800",
    letterSpacing: "-0.03em",
  },
  photoStyle: "Mining farms, ASICs en rangées, chaleur industrielle, orange électrique",
  graphicStyle: "Hash lines, blockchain blocks géométriques, mempool visualisations",
  iconography: "Orange Bitcoin sur fond sombre, symbole ₿ stylisé, hexagones",
  boxStyle: "Brun très sombre, border orange fine, hard shadow orange",
  titleStyle: "Extra-bold, orange vif sur très sombre, puissant",
  dividerStyle: "Ligne orange fine, marqueurs de blocs",
  dataVizStyle: "Price action chart orange, hash rate bars, adoption S-curve",
  globalTone: "Absolu, rare, immuable, confiance zéro",
  tailwind: {
    bg: "bg-[#060401]",
    bgSurface: "bg-[#100B04]",
    bgSurfaceAlt: "bg-[#1A1108]",
    text: "text-[#FFF8E1]",
    textMuted: "text-[#8A6230]",
    accent: "text-[#F7931A]",
    border: "border-[#2E1C08]",
    highlight: "text-[#FFBA50]",
    headerBg: "bg-[#0A0602]",
    footerBg: "bg-[#060401]",
  },
};

themes["defi-dune"] = {
  id: "defi-dune",
  name: "DeFi Dune",
  tagline: "Données on-chain, analytics temps réel",
  colors: {
    primary: "#100A05",
    secondary: "#1C1208",
    accent: "#E8662A",
    background: "#0A0603",
    surface: "#161008",
    surfaceAlt: "#20160C",
    text: "#F0E8D8",
    textMuted: "#8A7050",
    border: "#3A2210",
    highlight: "#FFA040",
    cmyk: { primary: "C:0 M:38 Y:68 K:94", secondary: "C:0 M:36 Y:58 K:89", accent: "C:0 M:56 Y:82 K:9" },
  },
  typography: {
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(42px, 5.5vw, 88px)",
    titleSize: "clamp(21px, 2.7vw, 42px)",
    subtitleSize: "clamp(12px, 1.6vw, 20px)",
    bodySize: "clamp(10px, 1.1vw, 13px)",
    captionSize: "clamp(7px, 0.85vw, 9px)",
    headingWeight: "600",
    letterSpacing: "-0.01em",
  },
  photoStyle: "Data visualisations DeFi, liquidity pools, fond sable chaud",
  graphicStyle: "Sand dune textures, data curves organiques, warm amber gradients",
  iconography: "Amber warm, swap arrows, liquidity icons, organic shapes",
  boxStyle: "Brun chaud, border amber, texture sable digitale",
  titleStyle: "Semi-bold amber sur très sombre, dashboard analytics",
  dividerStyle: "Gradient amber-brun chaud, line ondulée",
  dataVizStyle: "TVL charts amber-orange, volume bars chauds, DeFi metrics",
  globalTone: "Analytique, data-driven, intelligence protocol",
  tailwind: {
    bg: "bg-[#0A0603]",
    bgSurface: "bg-[#161008]",
    bgSurfaceAlt: "bg-[#20160C]",
    text: "text-[#F0E8D8]",
    textMuted: "text-[#8A7050]",
    accent: "text-[#E8662A]",
    border: "border-[#3A2210]",
    highlight: "text-[#FFA040]",
    headerBg: "bg-[#100A05]",
    footerBg: "bg-[#0A0603]",
  },
};

themes["nft-gallery"] = {
  id: "nft-gallery",
  name: "NFT Gallery",
  tagline: "Art numérique, propriété vérifiable, culture Web3",
  colors: {
    primary: "#FAFAF9",
    secondary: "#F3F0FF",
    accent: "#9B5DE5",
    background: "#FFFFFF",
    surface: "#F8F5FF",
    surfaceAlt: "#EDE8FF",
    text: "#1A0A2E",
    textMuted: "#6B4E8A",
    border: "#DDD4F5",
    highlight: "#FF6BF5",
    cmyk: { primary: "C:0 M:0 Y:1 K:2", secondary: "C:4 M:7 Y:0 K:0", accent: "C:33 M:60 Y:0 K:10" },
  },
  typography: {
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(42px, 5.5vw, 88px)",
    titleSize: "clamp(21px, 2.7vw, 42px)",
    subtitleSize: "clamp(12px, 1.6vw, 20px)",
    bodySize: "clamp(10px, 1.1vw, 13px)",
    captionSize: "clamp(7px, 0.85vw, 9px)",
    headingWeight: "700",
    letterSpacing: "-0.02em",
  },
  photoStyle: "Artwork NFT premium, galerie blanche, cadres collector haute résolution",
  graphicStyle: "Galerie clean whitespace, grilles artwork, metadata overlays",
  iconography: "Purple collector, wallet icons, ETH symbols stylisés, gallery marks",
  boxStyle: "Blanc galerie, border purple fine, ombre douce, radius généreux",
  titleStyle: "Space Grotesk Bold, purple foncé sur blanc, haute typographie",
  dividerStyle: "Ligne fine purple 15% opacity, air maximal",
  dataVizStyle: "Floor price charts purple, volume NFT bars, rarity curves",
  globalTone: "Créatif, exclusif, communauté culturelle Web3",
  tailwind: {
    bg: "bg-white",
    bgSurface: "bg-[#F8F5FF]",
    bgSurfaceAlt: "bg-[#EDE8FF]",
    text: "text-[#1A0A2E]",
    textMuted: "text-[#6B4E8A]",
    accent: "text-[#9B5DE5]",
    border: "border-[#DDD4F5]",
    highlight: "text-[#FF6BF5]",
    headerBg: "bg-[#FAFAF9]",
    footerBg: "bg-[#1A0A2E]",
  },
};

// ─── ENTERPRISE TECH ──────────────────────────────────────────────────────────

themes["vercel-dark"] = {
  id: "vercel-dark",
  name: "Vercel Dark",
  tagline: "Ship fast. Ship global. Zero configuration.",
  colors: {
    primary: "#000000",
    secondary: "#0A0A0A",
    accent: "#FFFFFF",
    background: "#000000",
    surface: "#111111",
    surfaceAlt: "#1A1A1A",
    text: "#EDEDED",
    textMuted: "#888888",
    border: "#333333",
    highlight: "#FFFFFF",
    cmyk: { primary: "C:0 M:0 Y:0 K:100", secondary: "C:0 M:0 Y:0 K:96", accent: "C:0 M:0 Y:0 K:0" },
  },
  typography: {
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(44px, 5.8vw, 92px)",
    titleSize: "clamp(22px, 2.8vw, 44px)",
    subtitleSize: "clamp(13px, 1.7vw, 21px)",
    bodySize: "clamp(10px, 1.2vw, 14px)",
    captionSize: "clamp(8px, 0.9vw, 10px)",
    headingWeight: "700",
    letterSpacing: "-0.04em",
  },
  photoStyle: "Interface sombre CLI, deployments log streams, infrastructure zéro-config",
  graphicStyle: "Grille minimale noire, typographie comme architecture, pixels précis",
  iconography: "White monoline strict, precision, Geist icons",
  boxStyle: "Noir absolu, border #333 très fine, radius 0, razor-sharp",
  titleStyle: "Inter Bold 700, blanc pur sur noir, letterspacing serré",
  dividerStyle: "1px #333 strict, no decoration, pure structure",
  dataVizStyle: "Blanc/gris sur noir, précision absolue, build analytics",
  globalTone: "Précis, frictionless, developer-first, obsession du détail",
  tailwind: {
    bg: "bg-black",
    bgSurface: "bg-[#111111]",
    bgSurfaceAlt: "bg-[#1A1A1A]",
    text: "text-[#EDEDED]",
    textMuted: "text-[#888888]",
    accent: "text-white",
    border: "border-[#333333]",
    highlight: "text-white",
    headerBg: "bg-black",
    footerBg: "bg-black",
  },
};

themes["linear-purple"] = {
  id: "linear-purple",
  name: "Linear Purple",
  tagline: "La vitesse comme standard, le design comme conviction",
  colors: {
    primary: "#0F0F13",
    secondary: "#141418",
    accent: "#5E6AD2",
    background: "#0A0A0E",
    surface: "#141420",
    surfaceAlt: "#1C1C2C",
    text: "#E8E8F2",
    textMuted: "#6B6B90",
    border: "#25253A",
    highlight: "#7C86E0",
    cmyk: { primary: "C:14 M:14 Y:0 K:93", secondary: "C:12 M:12 Y:0 K:90", accent: "C:57 M:52 Y:0 K:18" },
  },
  typography: {
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(44px, 5.8vw, 92px)",
    titleSize: "clamp(22px, 2.8vw, 44px)",
    subtitleSize: "clamp(13px, 1.7vw, 21px)",
    bodySize: "clamp(10px, 1.2vw, 14px)",
    captionSize: "clamp(8px, 0.9vw, 10px)",
    headingWeight: "700",
    letterSpacing: "-0.035em",
  },
  photoStyle: "Workflow interfaces sombres, issue boards, dark UI premium",
  graphicStyle: "Grilles de cartes indigo sombre, connexions nœuds, cycle views",
  iconography: "Indigo clair monoline, system icons précis, sharp",
  boxStyle: "Surface sombre indigo-shifted, border indigo subtil, radius 8px",
  titleStyle: "Inter Bold tight, violet-indigo sur très sombre, sprint feel",
  dividerStyle: "Trait horizontal 1px indigo opacity très faible, structure",
  dataVizStyle: "Velocity charts indigo, burndown curves, cycle time histograms",
  globalTone: "Opinionated, craftsman, design comme avantage compétitif",
  tailwind: {
    bg: "bg-[#0A0A0E]",
    bgSurface: "bg-[#141420]",
    bgSurfaceAlt: "bg-[#1C1C2C]",
    text: "text-[#E8E8F2]",
    textMuted: "text-[#6B6B90]",
    accent: "text-[#5E6AD2]",
    border: "border-[#25253A]",
    highlight: "text-[#7C86E0]",
    headerBg: "bg-[#0F0F13]",
    footerBg: "bg-[#0A0A0E]",
  },
};

themes["palantir-navy"] = {
  id: "palantir-navy",
  name: "Palantir Navy",
  tagline: "Intelligence opérationnelle, décisions critiques",
  colors: {
    primary: "#030B14",
    secondary: "#071525",
    accent: "#00B4D8",
    background: "#020910",
    surface: "#061422",
    surfaceAlt: "#0C2038",
    text: "#B8D4E8",
    textMuted: "#4A7090",
    border: "#0E2840",
    highlight: "#40D8F8",
    cmyk: { primary: "C:79 M:45 Y:0 K:92", secondary: "C:72 M:35 Y:0 K:85", accent: "C:100 M:21 Y:0 K:15" },
  },
  typography: {
    headingFont: "'IBM Plex Mono', monospace",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(40px, 5.2vw, 84px)",
    titleSize: "clamp(20px, 2.6vw, 40px)",
    subtitleSize: "clamp(11px, 1.5vw, 19px)",
    bodySize: "clamp(10px, 1.1vw, 13px)",
    captionSize: "clamp(7px, 0.85vw, 9px)",
    headingWeight: "500",
    letterSpacing: "0.02em",
  },
  photoStyle: "Situation rooms, data fusion centers, command infrastructure sombre",
  graphicStyle: "Maps overlay cyan, network graphs enterprise, Gotham-inspired",
  iconography: "Cyan froid monoline, système iconique strict, zéro ornement",
  boxStyle: "Marine profond, border cyan fine, corners précis, intelligence aesthetics",
  titleStyle: "IBM Plex Mono medium, cyan sur marine, precision opérationnelle",
  dividerStyle: "Ligne cyan 40% opacity, segment markers, tactical grid",
  dataVizStyle: "Cyan charts sur marine, geospatial overlays, mission-critical data",
  globalTone: "Mission-critical, confidentiel, force opérationnelle",
  tailwind: {
    bg: "bg-[#020910]",
    bgSurface: "bg-[#061422]",
    bgSurfaceAlt: "bg-[#0C2038]",
    text: "text-[#B8D4E8]",
    textMuted: "text-[#4A7090]",
    accent: "text-[#00B4D8]",
    border: "border-[#0E2840]",
    highlight: "text-[#40D8F8]",
    headerBg: "bg-[#030B14]",
    footerBg: "bg-[#020910]",
  },
};

themes["bloomberg-terminal"] = {
  id: "bloomberg-terminal",
  name: "Bloomberg Terminal",
  tagline: "L'ambre des marchés. La vitesse de la décision.",
  colors: {
    primary: "#000000",
    secondary: "#080808",
    accent: "#F5A623",
    background: "#000000",
    surface: "#0A0A0A",
    surfaceAlt: "#111111",
    text: "#F5A623",
    textMuted: "#8A6200",
    border: "#2A1E00",
    highlight: "#FFD580",
    cmyk: { primary: "C:0 M:0 Y:0 K:100", secondary: "C:0 M:0 Y:0 K:97", accent: "C:0 M:32 Y:86 K:4" },
  },
  typography: {
    headingFont: "'IBM Plex Mono', monospace",
    bodyFont: "'IBM Plex Mono', monospace",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(36px, 4.8vw, 78px)",
    titleSize: "clamp(18px, 2.4vw, 38px)",
    subtitleSize: "clamp(11px, 1.4vw, 18px)",
    bodySize: "clamp(10px, 1.1vw, 13px)",
    captionSize: "clamp(7px, 0.85vw, 9px)",
    headingWeight: "500",
    letterSpacing: "0.06em",
  },
  photoStyle: "Trading floors, écrans terminal orange, NYC financial district la nuit",
  graphicStyle: "ASCII charts amber, dot matrix displays, ticker tape layouts",
  iconography: "Amber monospace, symboles financiers, terminal glyphs",
  boxStyle: "Noir terminal, border amber #F5A623, style scan-line",
  titleStyle: "IBM Plex Mono caps, amber sur noir absolu, terminal feel",
  dividerStyle: "Ligne amber tirets, séquence de caractères",
  dataVizStyle: "OHLC amber charts, candlesticks, order book visualization",
  globalTone: "Autorité financière, information dense, vitesse décision",
  tailwind: {
    bg: "bg-black",
    bgSurface: "bg-[#0A0A0A]",
    bgSurfaceAlt: "bg-[#111111]",
    text: "text-[#F5A623]",
    textMuted: "text-[#8A6200]",
    accent: "text-[#F5A623]",
    border: "border-[#2A1E00]",
    highlight: "text-[#FFD580]",
    headerBg: "bg-black",
    footerBg: "bg-black",
  },
};

themes["nvidia-dgx"] = {
  id: "nvidia-dgx",
  name: "NVIDIA DGX",
  tagline: "Puissance de calcul ultime, infrastructure IA souveraine",
  colors: {
    primary: "#060806",
    secondary: "#0A100A",
    accent: "#76B900",
    background: "#030503",
    surface: "#091409",
    surfaceAlt: "#0F1E0F",
    text: "#E8F0E8",
    textMuted: "#4A6E4A",
    border: "#1A2E1A",
    highlight: "#90D020",
    cmyk: { primary: "C:8 M:0 Y:8 K:98", secondary: "C:10 M:0 Y:10 K:96", accent: "C:36 M:0 Y:100 K:27" },
  },
  typography: {
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(46px, 6vw, 96px)",
    titleSize: "clamp(23px, 2.9vw, 46px)",
    subtitleSize: "clamp(13px, 1.7vw, 21px)",
    bodySize: "clamp(10px, 1.2vw, 14px)",
    captionSize: "clamp(8px, 0.9vw, 10px)",
    headingWeight: "700",
    letterSpacing: "-0.02em",
  },
  photoStyle: "GPU racks DGX SuperPod, green LED cooling, datacenter IA",
  graphicStyle: "Circuit traces vertes, GPU dies macro, compute grids",
  iconography: "Vert NVIDIA sur très sombre, tech precision, GPU silhouettes",
  boxStyle: "Très sombre, border vert NVIDIA, corner tech style",
  titleStyle: "Space Grotesk Bold, vert #76B900 sur presque noir, impact",
  dividerStyle: "Ligne verte NVIDIA, circuit pattern subtil",
  dataVizStyle: "Training curves vertes, benchmark bars, FLOPS analytics",
  globalTone: "Performance absolue, AI sovereignty, compute as infrastructure",
  tailwind: {
    bg: "bg-[#030503]",
    bgSurface: "bg-[#091409]",
    bgSurfaceAlt: "bg-[#0F1E0F]",
    text: "text-[#E8F0E8]",
    textMuted: "text-[#4A6E4A]",
    accent: "text-[#76B900]",
    border: "border-[#1A2E1A]",
    highlight: "text-[#90D020]",
    headerBg: "bg-[#060806]",
    footerBg: "bg-[#030503]",
  },
};

// ─── HIGH-END / LUXURY TECH ───────────────────────────────────────────────────

themes["stripe-gradient"] = {
  id: "stripe-gradient",
  name: "Stripe Gradient",
  tagline: "Infrastructure paiement, confiance universelle",
  colors: {
    primary: "#F6F9FC",
    secondary: "#EEF3FF",
    accent: "#635BFF",
    background: "#FFFFFF",
    surface: "#F6F6FF",
    surfaceAlt: "#EEEEFF",
    text: "#0A0728",
    textMuted: "#5A5580",
    border: "#CCC8FF",
    highlight: "#8B85FF",
    cmyk: { primary: "C:2 M:2 Y:0 K:1", secondary: "C:6 M:5 Y:0 K:0", accent: "C:61 M:64 Y:0 K:0" },
  },
  typography: {
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(44px, 5.8vw, 92px)",
    titleSize: "clamp(22px, 2.8vw, 44px)",
    subtitleSize: "clamp(13px, 1.7vw, 21px)",
    bodySize: "clamp(10px, 1.2vw, 14px)",
    captionSize: "clamp(8px, 0.9vw, 10px)",
    headingWeight: "700",
    letterSpacing: "-0.03em",
  },
  photoStyle: "Gradient product shots blanc-violet, interface Stripe, trust signals",
  graphicStyle: "Gradients violet-indigo signature, courbes douces, cards flottantes",
  iconography: "Violet Stripe monoline, payment icons, trust badges",
  boxStyle: "Blanc+surface violet très pale, border violet subtle, radius généreux, shadow douce",
  titleStyle: "Inter Bold, violet profond sur blanc, confiance institutionnelle",
  dividerStyle: "Gradient violet→transparent, très subtil",
  dataVizStyle: "Revenue charts violet, conversion funnels, payment analytics",
  globalTone: "Confiance, simplicité, infrastructure invisible mais essentielle",
  tailwind: {
    bg: "bg-white",
    bgSurface: "bg-[#F6F6FF]",
    bgSurfaceAlt: "bg-[#EEEEFF]",
    text: "text-[#0A0728]",
    textMuted: "text-[#5A5580]",
    accent: "text-[#635BFF]",
    border: "border-[#CCC8FF]",
    highlight: "text-[#8B85FF]",
    headerBg: "bg-[#F6F9FC]",
    footerBg: "bg-[#0A0728]",
  },
};

themes["pitch-midnight"] = {
  id: "pitch-midnight",
  name: "Pitch Midnight",
  tagline: "Présentations de conviction, design comme arme",
  colors: {
    primary: "#07080F",
    secondary: "#0D0E18",
    accent: "#E8E8F5",
    background: "#040508",
    surface: "#0A0B14",
    surfaceAlt: "#10121E",
    text: "#F0F0FA",
    textMuted: "#5C5C80",
    border: "#1A1A2E",
    highlight: "#A0A0D0",
    cmyk: { primary: "C:44 M:37 Y:0 K:94", secondary: "C:40 M:32 Y:0 K:91", accent: "C:5 M:5 Y:0 K:4" },
  },
  typography: {
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(46px, 6.2vw, 100px)",
    titleSize: "clamp(23px, 3vw, 48px)",
    subtitleSize: "clamp(13px, 1.7vw, 21px)",
    bodySize: "clamp(10px, 1.2vw, 14px)",
    captionSize: "clamp(8px, 0.9vw, 10px)",
    headingWeight: "700",
    letterSpacing: "-0.04em",
  },
  photoStyle: "Présentations sombres premium, réunions NDA, boardroom high-stake",
  graphicStyle: "Dark mode premium, gradients subtils bleu-shifted, typographie as art",
  iconography: "Blanc cassé sur sombre bleu-noir, monoline élégant",
  boxStyle: "Bleu-noir profond, border 1px subtil, gradient intérieur soft",
  titleStyle: "Space Grotesk Extra-bold, blanc cassé sur midnight blue, conviction",
  dividerStyle: "1px bleu-blanc opacity 20%, ultra-clean",
  dataVizStyle: "Charts gris-blanc sur bleu noir, runway curves, growth projections",
  globalTone: "Conviction, storytelling premium, fundraising excellence",
  tailwind: {
    bg: "bg-[#040508]",
    bgSurface: "bg-[#0A0B14]",
    bgSurfaceAlt: "bg-[#10121E]",
    text: "text-[#F0F0FA]",
    textMuted: "text-[#5C5C80]",
    accent: "text-[#E8E8F5]",
    border: "border-[#1A1A2E]",
    highlight: "text-[#A0A0D0]",
    headerBg: "bg-[#07080F]",
    footerBg: "bg-[#040508]",
  },
};

themes["ghost-editorial"] = {
  id: "ghost-editorial",
  name: "Ghost Editorial",
  tagline: "Contenu sans friction, infrastructure éditoriale",
  colors: {
    primary: "#0A0A0A",
    secondary: "#111111",
    accent: "#FFD60A",
    background: "#000000",
    surface: "#111111",
    surfaceAlt: "#1A1A1A",
    text: "#F5F5F5",
    textMuted: "#666666",
    border: "#2A2A2A",
    highlight: "#FFE84D",
    cmyk: { primary: "C:0 M:0 Y:0 K:96", secondary: "C:0 M:0 Y:0 K:93", accent: "C:0 M:16 Y:96 K:0" },
  },
  typography: {
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(46px, 6vw, 96px)",
    titleSize: "clamp(23px, 2.9vw, 46px)",
    subtitleSize: "clamp(13px, 1.7vw, 21px)",
    bodySize: "clamp(10px, 1.2vw, 14px)",
    captionSize: "clamp(8px, 0.9vw, 10px)",
    headingWeight: "800",
    letterSpacing: "-0.04em",
  },
  photoStyle: "Studio éditorial sombre, highlight jaune, journalisme premium",
  graphicStyle: "Contraste maximal, accents jaune vif sur noir, édito fort",
  iconography: "Jaune vif sur noir, editorial marks, citation symbols",
  boxStyle: "Noir profond, border jaune thin, highlights éditoriaux",
  titleStyle: "Inter Black, jaune sur noir, impact éditorial maximum",
  dividerStyle: "Ligne jaune #FFD60A fine, ou dash éditorial",
  dataVizStyle: "Charts jaune sur noir, reader analytics, growth editorial",
  globalTone: "Indépendant, courageux, voix sans compromis",
  tailwind: {
    bg: "bg-black",
    bgSurface: "bg-[#111111]",
    bgSurfaceAlt: "bg-[#1A1A1A]",
    text: "text-[#F5F5F5]",
    textMuted: "text-[#666666]",
    accent: "text-[#FFD60A]",
    border: "border-[#2A2A2A]",
    highlight: "text-[#FFE84D]",
    headerBg: "bg-[#0A0A0A]",
    footerBg: "bg-black",
  },
};

themes["apple-silicon"] = {
  id: "apple-silicon",
  name: "Apple Silicon",
  tagline: "Performances natives, efficience absolue",
  colors: {
    primary: "#F5F5F7",
    secondary: "#E8E8EC",
    accent: "#0071E3",
    background: "#FFFFFF",
    surface: "#FBFBFD",
    surfaceAlt: "#F5F5F7",
    text: "#1D1D1F",
    textMuted: "#6E6E73",
    border: "#D2D2D7",
    highlight: "#0077ED",
    cmyk: { primary: "C:0 M:0 Y:0 K:4", secondary: "C:1 M:1 Y:0 K:9", accent: "C:100 M:50 Y:0 K:11" },
  },
  typography: {
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(48px, 6.5vw, 104px)",
    titleSize: "clamp(24px, 3.2vw, 52px)",
    subtitleSize: "clamp(14px, 1.8vw, 22px)",
    bodySize: "clamp(10px, 1.2vw, 14px)",
    captionSize: "clamp(8px, 0.9vw, 10px)",
    headingWeight: "600",
    letterSpacing: "-0.025em",
  },
  photoStyle: "Product shots aluminium brossé, silicon chip macro, espaces blancs Apple",
  graphicStyle: "Whitespace maximal, grille Apple 8pt, typographie ultra-précise",
  iconography: "SF-inspired monoline, gris aluminium, bleu lien Apple",
  boxStyle: "Blanc+surface très légère, ombre très douce, radius 12px, ultra-clean",
  titleStyle: "Inter SemiBold, gris Apple très foncé sur blanc, produit",
  dividerStyle: "1px #D2D2D7 fin Apple, largeur totale, respiration",
  dataVizStyle: "Barres bleu Apple, Charts Apple-style, clear labels, clean grid",
  globalTone: "Raffinement absolu, innovation discrète, premium accessible",
  tailwind: {
    bg: "bg-white",
    bgSurface: "bg-[#FBFBFD]",
    bgSurfaceAlt: "bg-[#F5F5F7]",
    text: "text-[#1D1D1F]",
    textMuted: "text-[#6E6E73]",
    accent: "text-[#0071E3]",
    border: "border-[#D2D2D7]",
    highlight: "text-[#0077ED]",
    headerBg: "bg-[#F5F5F7]",
    footerBg: "bg-[#1D1D1F]",
  },
};

themes["arc-iris"] = {
  id: "arc-iris",
  name: "Arc Iris",
  tagline: "Navigate with intention. Browse beautifully.",
  colors: {
    primary: "#FFFFFF",
    secondary: "#F8F5FF",
    accent: "#8B5CF6",
    background: "#FFFFFF",
    surface: "#FAF8FF",
    surfaceAlt: "#F3EEFF",
    text: "#1A0A2E",
    textMuted: "#6B5E85",
    border: "#DDD0F8",
    highlight: "#06B6D4",
    cmyk: { primary: "C:0 M:0 Y:0 K:0", secondary: "C:2 M:3 Y:0 K:0", accent: "C:44 M:64 Y:0 K:4" },
  },
  typography: {
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    monoFont: "'IBM Plex Mono', monospace",
    heroSize: "clamp(44px, 5.8vw, 92px)",
    titleSize: "clamp(22px, 2.8vw, 44px)",
    subtitleSize: "clamp(13px, 1.7vw, 21px)",
    bodySize: "clamp(10px, 1.2vw, 14px)",
    captionSize: "clamp(8px, 0.9vw, 10px)",
    headingWeight: "700",
    letterSpacing: "-0.025em",
  },
  photoStyle: "Browser UI coloré, gradient iris, spaces visuels, fond blanc lumineux",
  graphicStyle: "Dégradés iris violet→cyan, formes molles, whitespace généreux",
  iconography: "Violet Arc monoline, iris color moments, sidebar icons colorés",
  boxStyle: "Blanc, border violet léger, radius 16px, ombre froide violette",
  titleStyle: "Space Grotesk Bold, violet profond sur blanc, gradient accent text",
  dividerStyle: "Gradient iris violet→cyan, très doux, air maximal",
  dataVizStyle: "Barres gradient iris, usage charts colorés, retention curves",
  globalTone: "Playful precision, design-led, joyful productivity",
  tailwind: {
    bg: "bg-white",
    bgSurface: "bg-[#FAF8FF]",
    bgSurfaceAlt: "bg-[#F3EEFF]",
    text: "text-[#1A0A2E]",
    textMuted: "text-[#6B5E85]",
    accent: "text-[#8B5CF6]",
    border: "border-[#DDD0F8]",
    highlight: "text-[#06B6D4]",
    headerBg: "bg-white",
    footerBg: "bg-[#1A0A2E]",
  },
};

export const themeList: ArtDirection[] = Object.values(themes) as ArtDirection[];
export const defaultTheme: ArtDirection = themes["futuristic-infra"] as ArtDirection;
export { themes };
